/*
  Warnings:

  - You are about to drop the column `createdAt` on the `User` table. All the data in the column will be lost.

*/
-- AlterTable
ALTER TABLE "Cashier" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Invoice" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Manufacturer" ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "OrderLine" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Payment" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "PaymentMethod" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "ProductTransaction" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "ProductType" ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Profile" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "PromoDetail" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Promotion" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Store" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "StoreBranch" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "SubCategory" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "User" DROP COLUMN "createdAt",
ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);

-- AlterTable
ALTER TABLE "Warehouse" ALTER COLUMN "creationDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "creationDate" SET DATA TYPE TIMESTAMP(6),
ALTER COLUMN "lastUpdateDate" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdateDate" SET DATA TYPE TIMESTAMP(6);
